from typing import List

NATURE_SUBJECTS: dict[str, List[str]] = {
    "Biological sciences": [
        "Biochemistry",
        "Biological techniques",
        "Biophysics",
        "Biotechnology",
        "Cancer",
        "Cell biology",
        "Chemical biology",
        "Computational biology and bioinformatics",
        "Developmental biology",
        "Drug discovery",
        "Ecology",
        "Evolution",
        "Genetics",
        "Immunology",
        "Microbiology",
        "Molecular biology",
        "Neuroscience",
        "Physiology",
        "Plant sciences",
        "Psychology",
        "Stem cells",
        "Structural biology",
        "Systems biology",
        "Zoology",
    ],
    "Business and commerce": [
        "Business and management",
        "Economics",
        "Finance",
        "Information systems and information technology",
        "Operational research",
    ],
    "Earth and environmental sciences": [
        "Biogeochemistry",
        "Climate sciences",
        "Ecology",
        "Environmental sciences",
        "Environmental social sciences",
        "Hydrology",
        "Limnology",
        "Natural hazards",
        "Ocean sciences",
        "Planetary science",
        "Solid Earth sciences",
        "Space physics",
    ],
    "Health sciences": [
        "Anatomy",
        "Biomarkers",
        "Cardiology",
        "Diseases",
        "Endocrinology",
        "Gastroenterology",
        "Health care",
        "Health occupations",
        "Medical research",
        "Molecular medicine",
        "Nephrology",
        "Neurology",
        "Oncology",
        "Pathogenesis",
        "Rheumatology",
        "Risk factors",
        "Signs and symptoms",
        "Urology",
    ],
    "Humanities": [
        "Complex networks",
        "Cultural and media studies",
        "Health humanities",
        "History",
        "Language and linguistics",
        "Literature",
        "Medical humanities",
        "Philosophy",
        "Religion",
        "Theatre and performance studies",
    ],
    "Physical sciences": [
        "Astronomy and planetary science",
        "Chemistry",
        "Energy science and technology",
        "Engineering",
        "Materials science",
        "Mathematics and computing",
        "Nanoscience and technology",
        "Optics and photonics",
        "Physics",
    ],
    "Scientific community and society": [
        "Agriculture",
        "Business and industry",
        "Developing world",
        "Energy and society",
        "Forestry",
        "Geography",
        "Scientific community",
        "Social sciences",
        "Water resources",
    ],
    "Social science": [
        "Anthropology",
        "Business and management",
        "Complex networks",
        "Criminology",
        "Cultural and media studies",
        "Development studies",
        "Economics",
        "Education",
        "Environmental studies",
        "Finance",
        "Geography",
        "History",
        "Language and linguistics",
        "Politics and international relations",
        "Psychology",
        "Science, technology and society",
        "Social policy",
        "Sociology",
    ],
}
