RSS_FEEDS: dict[str, str] = {
    "Nature Acta Pharmacologica Sinica": "https://www.nature.com/aps.rss",
    "Nature BDJ In Practice": "https://www.nature.com/bdjinpractice.rss",
    "Nature BDJ Open": "https://www.nature.com/bdjopen.rss",
    "Nature BDJ Student": "https://www.nature.com/bdjstudent.rss",
    "Nature BDJ Team": "https://www.nature.com/bdjteam.rss",
    "Nature Biopharma Dealmakers": "https://www.nature.com/biopharmdeal.rss",
    "Nature BJC Reports": "https://www.nature.com/bjcreports.rss",
    "Nature Blood Cancer Journal": "https://www.nature.com/bcj.rss",
    "Nature Bone Marrow Transplantation": "https://www.nature.com/bmt.rss",
    "Nature Bone Research": "https://www.nature.com/boneres.rss",
    "Nature British Dental Journal": "https://www.nature.com/bdj.rss",
    "Nature British Journal of Cancer": "https://www.nature.com/bjc.rss",
    "Nature Cancer Gene Therapy": "https://www.nature.com/cgt.rss",
    "Nature Cell Death & Differentiation": "https://www.nature.com/cdd.rss",
    "Nature Cell Death & Disease": "https://www.nature.com/cddis.rss",
    "Nature Cell Death Discovery": "https://www.nature.com/cddiscovery.rss",
    "Nature Cell Discovery": "https://www.nature.com/celldisc.rss",
    "Nature Cell Research": "https://www.nature.com/cr.rss",
    "Nature Cellular & Molecular Immunology": "https://www.nature.com/cmi.rss",
    "Nature Communications Biology": "https://www.nature.com/commsbio.rss",
    "Nature Communications Chemistry": "https://www.nature.com/commschem.rss",
    "Nature Communications Earth & Environment": "https://www.nature.com/commsenv.rss",
    "Nature Communications Engineering": "https://www.nature.com/commseng.rss",
    "Nature Communications Materials": "https://www.nature.com/commsmat.rss",
    "Nature Communications Medicine": "https://www.nature.com/commsmed.rss",
    "Nature Communications Physics": "https://www.nature.com/commsphys.rss",
    "Nature Communications Psychology": "https://www.nature.com/commspsychol.rss",
    "Nature European Journal of Clinical Nutrition": "https://www.nature.com/ejcn.rss",
    "Nature European Journal of Human Genetics": "https://www.nature.com/ejhg.rss",
    "Nature Evidence-Based Dentistry": "https://www.nature.com/ebd.rss",
    "Nature Experimental & Molecular Medicine": "https://www.nature.com/emm.rss",
    "Nature Eye": "https://www.nature.com/eye.rss",
    "Nature Gene Therapy": "https://www.nature.com/gt.rss",
    "Nature Genes & Immunity": "https://www.nature.com/gene.rss",
    "Nature Heredity": "https://www.nature.com/hdy.rss",
    "Nature Human Genome Variation": "https://www.nature.com/hgv.rss",
    "Nature Humanities and Social Sciences Communications": "https://www.nature.com/palcomms.rss",
    "Nature Hypertension Research": "https://www.nature.com/hr.rss",
    "Nature International Journal of Impotence Research": "https://www.nature.com/ijir.rss",
    "Nature International Journal of Obesity": "https://www.nature.com/ijo.rss",
    "Nature International Journal of Obesity Supplements": "https://www.nature.com/ijosup.rss",
    "Nature International Journal of Oral Science": "https://www.nature.com/ijos.rss",
    "Nature ISME Communications": "https://www.nature.com/ismecomms.rss",
    "Nature The ISME Journal": "https://www.nature.com/ismej.rss",
    "Nature The Journal of Antibiotics": "https://www.nature.com/ja.rss",
    "Nature Journal of Exposure Science & Environmental Epidemiology": "https://www.nature.com/jes.rss",
    "Nature Journal of Human Genetics": "https://www.nature.com/jhg.rss",
    "Nature Journal of Human Hypertension": "https://www.nature.com/jhh.rss",
    "Nature Journal of Perinatology": "https://www.nature.com/jp.rss",
    "Nature Lab Animal": "https://www.nature.com/laban.rss",
    "Nature Laboratory Investigation": "https://www.nature.com/labinvest.rss",
    "Nature Leukemia": "https://www.nature.com/leu.rss",
    "Nature Leukemia Supplements": "https://www.nature.com/leusup.rss",
    "Nature Light: Science & Applications": "https://www.nature.com/lsa.rss",
    "Nature Microsystems & Nanoengineering": "https://www.nature.com/micronano.rss",
    "Nature Modern Pathology": "https://www.nature.com/modpathol.rss",
    "Nature Molecular Psychiatry": "https://www.nature.com/mp.rss",
    "Nature Mucosal Immunology": "https://www.nature.com/mi.rss",
    "Nature": "https://www.nature.com/nature.rss",
    "Nature Africa": "https://www.nature.com/natafrica.rss",
    "Nature Aging": "https://www.nature.com/nataging.rss",
    "Nature Astronomy": "https://www.nature.com/natastron.rss",
    "Nature Biomedical Engineering": "https://www.nature.com/natbiomedeng.rss",
    "Nature Biotechnology": "https://www.nature.com/nbt.rss",
    "Nature Cancer": "https://www.nature.com/natcancer.rss",
    "Nature Cardiovascular Research": "https://www.nature.com/natcardiovascres.rss",
    "Nature Catalysis": "https://www.nature.com/natcatal.rss",
    "Nature Cell Biology": "https://www.nature.com/ncb.rss",
    "Nature Chemical Biology": "https://www.nature.com/nchembio.rss",
    "Nature Chemical Engineering": "https://www.nature.com/natchemeng.rss",
    "Nature Chemistry": "https://www.nature.com/nchem.rss",
    "Nature Cities": "https://www.nature.com/natcities.rss",
    "Nature Climate Change": "https://www.nature.com/nclimate.rss",
    "Nature Communications": "https://www.nature.com/ncomms.rss",
    "Nature Computational Science": "https://www.nature.com/natcomputsci.rss",
    "Nature Digest": "https://www.nature.com/ndigest.rss",
    "Nature Ecology & Evolution": "https://www.nature.com/natecolevol.rss",
    "Nature Electronics": "https://www.nature.com/natelectron.rss",
    "Nature Energy": "https://www.nature.com/nenergy.rss",
    "Nature Food": "https://www.nature.com/natfood.rss",
    "Nature Genetics": "https://www.nature.com/ng.rss",
    "Nature Geoscience": "https://www.nature.com/ngeo.rss",
    "Nature Human Behaviour": "https://www.nature.com/nathumbehav.rss",
    "Nature Immunology": "https://www.nature.com/ni.rss",
    "Nature India": "https://www.nature.com/natindia.rss",
    "Nature Italy": "https://www.nature.com/natitaly.rss",
    "Nature Machine Intelligence": "https://www.nature.com/natmachintell.rss",
    "Nature Materials": "https://www.nature.com/nmat.rss",
    "Nature Medicine": "https://www.nature.com/nm.rss",
    "Nature Mental Health": "https://www.nature.com/natmentalhealth.rss",
    "Nature Metabolism": "https://www.nature.com/natmetab.rss",
    "Nature Methods": "https://www.nature.com/nmeth.rss",
    "Nature Microbiology": "https://www.nature.com/nmicrobiol.rss",
    "Nature Nanotechnology": "https://www.nature.com/nnano.rss",
    "Nature Neuroscience": "https://www.nature.com/neuro.rss",
    "Nature Photonics": "https://www.nature.com/nphoton.rss",
    "Nature Physics": "https://www.nature.com/nphys.rss",
    "Nature Plants": "https://www.nature.com/nplants.rss",
    "Nature Protocols": "https://www.nature.com/nprot.rss",
    "Nature Reviews Bioengineering": "https://www.nature.com/natrevbioeng.rss",
    "Nature Reviews Cancer": "https://www.nature.com/nrc.rss",
    "Nature Reviews Cardiology": "https://www.nature.com/nrcardio.rss",
    "Nature Reviews Chemistry": "https://www.nature.com/natrevchem.rss",
    "Nature Reviews Clean Technology": "https://www.nature.com/nrct.rss",
    "Nature Reviews Clinical Oncology": "https://www.nature.com/nrclinonc.rss",
    "Nature Reviews Disease Primers": "https://www.nature.com/nrdp.rss",
    "Nature Reviews Drug Discovery": "https://www.nature.com/nrd.rss",
    "Nature Reviews Earth & Environment": "https://www.nature.com/natrevearthenviron.rss",
    "Nature Reviews Electrical Engineering": "https://www.nature.com/natrevelectreng.rss",
    "Nature Reviews Endocrinology": "https://www.nature.com/nrendo.rss",
    "Nature Reviews Gastroenterology & Hepatology": "https://www.nature.com/nrgastro.rss",
    "Nature Reviews Genetics": "https://www.nature.com/nrg.rss",
    "Nature Reviews Immunology": "https://www.nature.com/nri.rss",
    "Nature Reviews Materials": "https://www.nature.com/natrevmats.rss",
    "Nature Reviews Methods Primers": "https://www.nature.com/nrmp.rss",
    "Nature Reviews Microbiology": "https://www.nature.com/nrmicro.rss",
    "Nature Reviews Molecular Cell Biology": "https://www.nature.com/nrm.rss",
    "Nature Reviews Nephrology": "https://www.nature.com/nrneph.rss",
    "Nature Reviews Neurology": "https://www.nature.com/nrneurol.rss",
    "Nature Reviews Neuroscience": "https://www.nature.com/nrn.rss",
    "Nature Reviews Physics": "https://www.nature.com/natrevphys.rss",
    "Nature Reviews Psychology": "https://www.nature.com/nrpsychol.rss",
    "Nature Reviews Rheumatology": "https://www.nature.com/nrrheum.rss",
    "Nature Reviews Urology": "https://www.nature.com/nrurol.rss",
    "Nature Structural & Molecular Biology": "https://www.nature.com/nsmb.rss",
    "Nature Sustainability": "https://www.nature.com/natsustain.rss",
    "Nature Synthesis": "https://www.nature.com/natsynth.rss",
    "Nature Water": "https://www.nature.com/natwater.rss",
    "Nature Neuropsychopharmacology": "https://www.nature.com/npp.rss",
    "Nature NPG Asia Materials": "https://www.nature.com/am.rss",
    "Nature npj 2D Materials and Applications": "https://www.nature.com/npj2dmaterials.rss",
    "Nature npj Advanced Manufacturing": "https://www.nature.com/npjadvmanuf.rss",
    "Nature npj Aging": "https://www.nature.com/npjamd.rss",
    "Nature npj Antimicrobials and Resistance": "https://www.nature.com/npjamar.rss",
    "Nature npj Biodiversity": "https://www.nature.com/npjbiodivers.rss",
    "Nature npj Biofilms and Microbiomes": "https://www.nature.com/npjbiofilms.rss",
    "Nature npj Biological Physics and Mechanics": "https://www.nature.com/npjbiolphysmech.rss",
    "Nature npj Biological Timing and Sleep": "https://www.nature.com/npjbts.rss",
    "Nature npj Biosensing": "https://www.nature.com/npjbiosensing.rss",
    "Nature npj Breast Cancer": "https://www.nature.com/npjbcancer.rss",
    "Nature npj Cardiovascular Health": "https://www.nature.com/npjcardiohealth.rss",
    "Nature npj Clean Water": "https://www.nature.com/npjcleanwater.rss",
    "Nature npj Climate Action": "https://www.nature.com/npjclimataction.rss",
    "Nature npj Climate and Atmospheric Science": "https://www.nature.com/npjclimatsci.rss",
    "Nature npj Complexity": "https://www.nature.com/npjcomplex.rss",
    "Nature npj Computational Materials": "https://www.nature.com/npjcompumats.rss",
    "Nature npj Digital Medicine": "https://www.nature.com/npjdigitalmed.rss",
    "Nature npj Flexible Electronics": "https://www.nature.com/npjflexelectron.rss",
    "Nature npj Genomic Medicine": "https://www.nature.com/npjgenmed.rss",
    "Nature npj Gut and Liver": "https://www.nature.com/npjgutliver.rss",
    "Nature npj Imaging": "https://www.nature.com/npjimaging.rss",
    "Nature npj Materials Degradation": "https://www.nature.com/npjmatdeg.rss",
    "Nature npj Materials Sustainability": "https://www.nature.com/npjmatsustain.rss",
    "Nature npj Mental Health Research": "https://www.nature.com/npjmentalhealth.rss",
    "Nature npj Metabolic Health and Disease": "https://www.nature.com/npjmetabhealth.rss",
    "Nature npj Microgravity": "https://www.nature.com/npjmgrav.rss",
    "Nature npj Nanophotonics": "https://www.nature.com/npjnanophoton.rss",
    "Nature npj Natural Hazards": "https://www.nature.com/npjnathazards.rss",
    "Nature npj Ocean Sustainability": "https://www.nature.com/npjoceansustain.rss",
    "Nature npj Parkinson's Disease": "https://www.nature.com/npjparkd.rss",
    "Nature npj Precision Oncology": "https://www.nature.com/npjprecisiononcology.rss",
    "Nature npj Primary Care Respiratory Medicine": "https://www.nature.com/npjpcrm.rss",
    "Nature npj Quantum Information": "https://www.nature.com/npjqi.rss",
    "Nature npj Quantum Materials": "https://www.nature.com/npjquantmats.rss",
    "Nature npj Regenerative Medicine": "https://www.nature.com/npjregenmed.rss",
    "Nature npj Robotics": "https://www.nature.com/npjrobot.rss",
    "Nature npj Science of Food": "https://www.nature.com/npjscifood.rss",
    "Nature npj Science of Learning": "https://www.nature.com/npjscilearn.rss",
    "Nature npj Spintronics": "https://www.nature.com/npjspintronics.rss",
    "Nature npj Sustainable Agriculture": "https://www.nature.com/npjsustainagric.rss",
    "Nature npj Sustainable Mobility and Transport": "https://www.nature.com/npjsustainmobil.rss",
    "Nature npj Systems Biology and Applications": "https://www.nature.com/npjsba.rss",
    "Nature npj Unconventional Computing": "https://www.nature.com/npjunconvcomput.rss",
    "Nature npj Urban Sustainability": "https://www.nature.com/npjurbansustain.rss",
    "Nature npj Vaccines": "https://www.nature.com/npjvaccines.rss",
    "Nature npj Viruses": "https://www.nature.com/npjviruses.rss",
    "Nature npj Women's Health": "https://www.nature.com/npjwomenshealth.rss",
    "Nature NPP-Psychiatry and Neuroscience": "https://www.nature.com/dpn.rss",
    "Nature Nutrition & Diabetes": "https://www.nature.com/nutd.rss",
    "Nature Oncogene": "https://www.nature.com/onc.rss",
    "Nature Oncogenesis": "https://www.nature.com/oncsis.rss",
    "Nature Pediatric Research": "https://www.nature.com/pr.rss",
    "Nature The Pharmacogenomics Journal": "https://www.nature.com/tpj.rss",
    "Nature Polymer Journal": "https://www.nature.com/pj.rss",
    "Nature Prostate Cancer and Prostatic Diseases": "https://www.nature.com/pcan.rss",
    "Nature Schizophrenia": "https://www.nature.com/npjschz.rss",
    "Nature Scientific American": "https://www.nature.com/scientificamerican.rss",
    "Nature Scientific American Mind": "https://www.nature.com/scientificamericanmind.rss",
    "Nature Scientific Data": "https://www.nature.com/sdata.rss",
    "Nature Scientific Reports": "https://www.nature.com/srep.rss",
    "Nature Signal Transduction and Targeted Therapy": "https://www.nature.com/sigtrans.rss",
    "Nature Spinal Cord": "https://www.nature.com/sc.rss",
    "Nature Spinal Cord Series and Cases": "https://www.nature.com/scsandc.rss",
    "Nature Translational Psychiatry": "https://www.nature.com/tp.rss",
}

RESEARCH_ARTICLE_CATALOG: dict[str, str] = {
    "Nature Acta Pharmacologica Sinica": "https://www.nature.com/aps/research-articles",
    "Nature BDJ In Practice": "https://www.nature.com/bdjinpractice/research-articles",
    "Nature BDJ Open": "https://www.nature.com/bdjopen/research-articles",
    "Nature BDJ Student": "https://www.nature.com/bdjstudent/research-articles",
    "Nature BDJ Team": "https://www.nature.com/bdjteam/research-articles",
    "Nature Biopharma Dealmakers": "https://www.nature.com/biopharmdeal/research-articles",
    "Nature BJC Reports": "https://www.nature.com/bjcreports/research-articles",
    "Nature Blood Cancer Journal": "https://www.nature.com/bcj/research-articles",
    "Nature Bone Marrow Transplantation": "https://www.nature.com/bmt/research-articles",
    "Nature Bone Research": "https://www.nature.com/boneres/research-articles",
    "Nature British Dental Journal": "https://www.nature.com/bdj/research-articles",
    "Nature British Journal of Cancer": "https://www.nature.com/bjc/research-articles",
    "Nature Cancer Gene Therapy": "https://www.nature.com/cgt/research-articles",
    "Nature Cell Death & Differentiation": "https://www.nature.com/cdd/research-articles",
    "Nature Cell Death & Disease": "https://www.nature.com/cddis/research-articles",
    "Nature Cell Death Discovery": "https://www.nature.com/cddiscovery/research-articles",
    "Nature Cell Discovery": "https://www.nature.com/celldisc/research-articles",
    "Nature Cell Research": "https://www.nature.com/cr/research-articles",
    "Nature Cellular & Molecular Immunology": "https://www.nature.com/cmi/research-articles",
    "Nature Communications Biology": "https://www.nature.com/commsbio/research-articles",
    "Nature Communications Chemistry": "https://www.nature.com/commschem/research-articles",
    "Nature Communications Earth & Environment": "https://www.nature.com/commsenv/research-articles",
    "Nature Communications Engineering": "https://www.nature.com/commseng/research-articles",
    "Nature Communications Materials": "https://www.nature.com/commsmat/research-articles",
    "Nature Communications Medicine": "https://www.nature.com/commsmed/research-articles",
    "Nature Communications Physics": "https://www.nature.com/commsphys/research-articles",
    "Nature Communications Psychology": "https://www.nature.com/commspsychol/research-articles",
    "Nature European Journal of Clinical Nutrition": "https://www.nature.com/ejcn/research-articles",
    "Nature European Journal of Human Genetics": "https://www.nature.com/ejhg/research-articles",
    "Nature Evidence-Based Dentistry": "https://www.nature.com/ebd/research-articles",
    "Nature Experimental & Molecular Medicine": "https://www.nature.com/emm/research-articles",
    "Nature Eye": "https://www.nature.com/eye/research-articles",
    "Nature Gene Therapy": "https://www.nature.com/gt/research-articles",
    "Nature Genes & Immunity": "https://www.nature.com/gene/research-articles",
    "Nature Heredity": "https://www.nature.com/hdy/research-articles",
    "Nature Human Genome Variation": "https://www.nature.com/hgv/research-articles",
    "Nature Humanities and Social Sciences Communications": "https://www.nature.com/palcomms/research-articles",
    "Nature Hypertension Research": "https://www.nature.com/hr/research-articles",
    "Nature International Journal of Impotence Research": "https://www.nature.com/ijir/research-articles",
    "Nature International Journal of Obesity": "https://www.nature.com/ijo/research-articles",
    "Nature International Journal of Obesity Supplements": "https://www.nature.com/ijosup/research-articles",
    "Nature International Journal of Oral Science": "https://www.nature.com/ijos/research-articles",
    "Nature ISME Communications": "https://www.nature.com/ismecomms/research-articles",
    "Nature The ISME Journal": "https://www.nature.com/ismej/research-articles",
    "Nature The Journal of Antibiotics": "https://www.nature.com/ja/research-articles",
    "Nature Journal of Exposure Science & Environmental Epidemiology": "https://www.nature.com/jes/research-articles",
    "Nature Journal of Human Genetics": "https://www.nature.com/jhg/research-articles",
    "Nature Journal of Human Hypertension": "https://www.nature.com/jhh/research-articles",
    "Nature Journal of Perinatology": "https://www.nature.com/jp/research-articles",
    "Nature Lab Animal": "https://www.nature.com/laban/research-articles",
    "Nature Laboratory Investigation": "https://www.nature.com/labinvest/research-articles",
    "Nature Leukemia": "https://www.nature.com/leu/research-articles",
    "Nature Leukemia Supplements": "https://www.nature.com/leusup/research-articles",
    "Nature Light: Science & Applications": "https://www.nature.com/lsa/research-articles",
    "Nature Microsystems & Nanoengineering": "https://www.nature.com/micronano/research-articles",
    "Nature Modern Pathology": "https://www.nature.com/modpathol/research-articles",
    "Nature Molecular Psychiatry": "https://www.nature.com/mp/research-articles",
    "Nature Mucosal Immunology": "https://www.nature.com/mi/research-articles",
    "Nature": "https://www.nature.com/nature/research-articles",
    "Nature Africa": "https://www.nature.com/natafrica/research-articles",
    "Nature Aging": "https://www.nature.com/nataging/research-articles",
    "Nature Astronomy": "https://www.nature.com/natastron/research-articles",
    "Nature Biomedical Engineering": "https://www.nature.com/natbiomedeng/research-articles",
    "Nature Biotechnology": "https://www.nature.com/nbt/research-articles",
    "Nature Cancer": "https://www.nature.com/natcancer/research-articles",
    "Nature Cardiovascular Research": "https://www.nature.com/natcardiovascres/research-articles",
    "Nature Catalysis": "https://www.nature.com/natcatal/research-articles",
    "Nature Cell Biology": "https://www.nature.com/ncb/research-articles",
    "Nature Chemical Biology": "https://www.nature.com/nchembio/research-articles",
    "Nature Chemical Engineering": "https://www.nature.com/natchemeng/research-articles",
    "Nature Chemistry": "https://www.nature.com/nchem/research-articles",
    "Nature Cities": "https://www.nature.com/natcities/research-articles",
    "Nature Climate Change": "https://www.nature.com/nclimate/research-articles",
    "Nature Communications": "https://www.nature.com/ncomms/research-articles",
    "Nature Computational Science": "https://www.nature.com/natcomputsci/research-articles",
    "Nature Digest": "https://www.nature.com/ndigest/research-articles",
    "Nature Ecology & Evolution": "https://www.nature.com/natecolevol/research-articles",
    "Nature Electronics": "https://www.nature.com/natelectron/research-articles",
    "Nature Energy": "https://www.nature.com/nenergy/research-articles",
    "Nature Food": "https://www.nature.com/natfood/research-articles",
    "Nature Genetics": "https://www.nature.com/ng/research-articles",
    "Nature Geoscience": "https://www.nature.com/ngeo/research-articles",
    "Nature Human Behaviour": "https://www.nature.com/nathumbehav/research-articles",
    "Nature Immunology": "https://www.nature.com/ni/research-articles",
    "Nature India": "https://www.nature.com/natindia/research-articles",
    "Nature Italy": "https://www.nature.com/natitaly/research-articles",
    "Nature Machine Intelligence": "https://www.nature.com/natmachintell/research-articles",
    "Nature Materials": "https://www.nature.com/nmat/research-articles",
    "Nature Medicine": "https://www.nature.com/nm/research-articles",
    "Nature Mental Health": "https://www.nature.com/natmentalhealth/research-articles",
    "Nature Metabolism": "https://www.nature.com/natmetab/research-articles",
    "Nature Methods": "https://www.nature.com/nmeth/research-articles",
    "Nature Microbiology": "https://www.nature.com/nmicrobiol/research-articles",
    "Nature Nanotechnology": "https://www.nature.com/nnano/research-articles",
    "Nature Neuroscience": "https://www.nature.com/neuro/research-articles",
    "Nature Photonics": "https://www.nature.com/nphoton/research-articles",
    "Nature Physics": "https://www.nature.com/nphys/research-articles",
    "Nature Plants": "https://www.nature.com/nplants/research-articles",
    "Nature Protocols": "https://www.nature.com/nprot/research-articles",
    "Nature Reviews Biodiversity": "https://www.nature.com/nrbd/research-articles",
    "Nature Reviews Bioengineering": "https://www.nature.com/natrevbioeng/research-articles",
    "Nature Reviews Cancer": "https://www.nature.com/nrc/research-articles",
    "Nature Reviews Cardiology": "https://www.nature.com/nrcardio/research-articles",
    "Nature Reviews Chemistry": "https://www.nature.com/natrevchem/research-articles",
    "Nature Reviews Clean Technology": "https://www.nature.com/nrct/research-articles",
    "Nature Reviews Clinical Oncology": "https://www.nature.com/nrclinonc/research-articles",
    "Nature Reviews Disease Primers": "https://www.nature.com/nrdp/research-articles",
    "Nature Reviews Drug Discovery": "https://www.nature.com/nrd/research-articles",
    "Nature Reviews Earth & Environment": "https://www.nature.com/natrevearthenviron/research-articles",
    "Nature Reviews Electrical Engineering": "https://www.nature.com/natrevelectreng/research-articles",
    "Nature Reviews Endocrinology": "https://www.nature.com/nrendo/research-articles",
    "Nature Reviews Gastroenterology & Hepatology": "https://www.nature.com/nrgastro/research-articles",
    "Nature Reviews Genetics": "https://www.nature.com/nrg/research-articles",
    "Nature Reviews Immunology": "https://www.nature.com/nri/research-articles",
    "Nature Reviews Materials": "https://www.nature.com/natrevmats/research-articles",
    "Nature Reviews Methods Primers": "https://www.nature.com/nrmp/research-articles",
    "Nature Reviews Microbiology": "https://www.nature.com/nrmicro/research-articles",
    "Nature Reviews Molecular Cell Biology": "https://www.nature.com/nrm/research-articles",
    "Nature Reviews Nephrology": "https://www.nature.com/nrneph/research-articles",
    "Nature Reviews Neurology": "https://www.nature.com/nrneurol/research-articles",
    "Nature Reviews Neuroscience": "https://www.nature.com/nrn/research-articles",
    "Nature Reviews Physics": "https://www.nature.com/natrevphys/research-articles",
    "Nature Reviews Psychology": "https://www.nature.com/nrpsychol/research-articles",
    "Nature Reviews Rheumatology": "https://www.nature.com/nrrheum/research-articles",
    "Nature Reviews Urology": "https://www.nature.com/nrurol/research-articles",
    "Nature Structural & Molecular Biology": "https://www.nature.com/nsmb/research-articles",
    "Nature Sustainability": "https://www.nature.com/natsustain/research-articles",
    "Nature Synthesis": "https://www.nature.com/natsynth/research-articles",
    "Nature Water": "https://www.nature.com/natwater/research-articles",
    "Nature Neuropsychopharmacology": "https://www.nature.com/npp/research-articles",
    "Nature NPG Asia Materials": "https://www.nature.com/am/research-articles",
    "Nature npj 2D Materials and Applications": "https://www.nature.com/npj2dmaterials/research-articles",
    "Nature npj Advanced Manufacturing": "https://www.nature.com/npjadvmanuf/research-articles",
    "Nature npj Aging": "https://www.nature.com/npjamd/research-articles",
    "Nature npj Antimicrobials and Resistance": "https://www.nature.com/npjamar/research-articles",
    "Nature npj Biodiversity": "https://www.nature.com/npjbiodivers/research-articles",
    "Nature npj Biofilms and Microbiomes": "https://www.nature.com/npjbiofilms/research-articles",
    "Nature npj Biological Physics and Mechanics": "https://www.nature.com/npjbiolphysmech/research-articles",
    "Nature npj Biological Timing and Sleep": "https://www.nature.com/npjbts/research-articles",
    "Nature npj Biosensing": "https://www.nature.com/npjbiosensing/research-articles",
    "Nature npj Breast Cancer": "https://www.nature.com/npjbcancer/research-articles",
    "Nature npj Cardiovascular Health": "https://www.nature.com/npjcardiohealth/research-articles",
    "Nature npj Clean Water": "https://www.nature.com/npjcleanwater/research-articles",
    "Nature npj Climate Action": "https://www.nature.com/npjclimataction/research-articles",
    "Nature npj Climate and Atmospheric Science": "https://www.nature.com/npjclimatsci/research-articles",
    "Nature npj Complexity": "https://www.nature.com/npjcomplex/research-articles",
    "Nature npj Computational Materials": "https://www.nature.com/npjcompumats/research-articles",
    "Nature npj Digital Medicine": "https://www.nature.com/npjdigitalmed/research-articles",
    "Nature npj Flexible Electronics": "https://www.nature.com/npjflexelectron/research-articles",
    "Nature npj Genomic Medicine": "https://www.nature.com/npjgenmed/research-articles",
    "Nature npj Gut and Liver": "https://www.nature.com/npjgutliver/research-articles",
    "Nature npj Imaging": "https://www.nature.com/npjimaging/research-articles",
    "Nature npj Materials Degradation": "https://www.nature.com/npjmatdeg/research-articles",
    "Nature npj Materials Sustainability": "https://www.nature.com/npjmatsustain/research-articles",
    "Nature npj Mental Health Research": "https://www.nature.com/npjmentalhealth/research-articles",
    "Nature npj Metabolic Health and Disease": "https://www.nature.com/npjmetabhealth/research-articles",
    "Nature npj Microgravity": "https://www.nature.com/npjmgrav/research-articles",
    "Nature npj Nanophotonics": "https://www.nature.com/npjnanophoton/research-articles",
    "Nature npj Natural Hazards": "https://www.nature.com/npjnathazards/research-articles",
    "Nature npj Ocean Sustainability": "https://www.nature.com/npjoceansustain/research-articles",
    "Nature npj Parkinson's Disease": "https://www.nature.com/npjparkd/research-articles",
    "Nature npj Precision Oncology": "https://www.nature.com/npjprecisiononcology/research-articles",
    "Nature npj Primary Care Respiratory Medicine": "https://www.nature.com/npjpcrm/research-articles",
    "Nature npj Quantum Information": "https://www.nature.com/npjqi/research-articles",
    "Nature npj Quantum Materials": "https://www.nature.com/npjquantmats/research-articles",
    "Nature npj Regenerative Medicine": "https://www.nature.com/npjregenmed/research-articles",
    "Nature npj Robotics": "https://www.nature.com/npjrobot/research-articles",
    "Nature npj Science of Food": "https://www.nature.com/npjscifood/research-articles",
    "Nature npj Science of Learning": "https://www.nature.com/npjscilearn/research-articles",
    "Nature npj Spintronics": "https://www.nature.com/npjspintronics/research-articles",
    "Nature npj Sustainable Agriculture": "https://www.nature.com/npjsustainagric/research-articles",
    "Nature npj Sustainable Mobility and Transport": "https://www.nature.com/npjsustainmobil/research-articles",
    "Nature npj Systems Biology and Applications": "https://www.nature.com/npjsba/research-articles",
    "Nature npj Unconventional Computing": "https://www.nature.com/npjunconvcomput/research-articles",
    "Nature npj Urban Sustainability": "https://www.nature.com/npjurbansustain/research-articles",
    "Nature npj Vaccines": "https://www.nature.com/npjvaccines/research-articles",
    "Nature npj Viruses": "https://www.nature.com/npjviruses/research-articles",
    "Nature npj Women's Health": "https://www.nature.com/npjwomenshealth/research-articles",
    "Nature NPP-Psychiatry and Neuroscience": "https://www.nature.com/dpn/research-articles",
    "Nature Nutrition & Diabetes": "https://www.nature.com/nutd/research-articles",
    "Nature Oncogene": "https://www.nature.com/onc/research-articles",
    "Nature Oncogenesis": "https://www.nature.com/oncsis/research-articles",
    "Nature Pediatric Research": "https://www.nature.com/pr/research-articles",
    "Nature The Pharmacogenomics Journal": "https://www.nature.com/tpj/research-articles",
    "Nature Polymer Journal": "https://www.nature.com/pj/research-articles",
    "Nature Prostate Cancer and Prostatic Diseases": "https://www.nature.com/pcan/research-articles",
    "Nature Schizophrenia": "https://www.nature.com/npjschz/research-articles",
    "Nature Scientific American": "https://www.nature.com/scientificamerican/research-articles",
    "Nature Scientific American Mind": "https://www.nature.com/scientificamericanmind/research-articles",
    "Nature Scientific Data": "https://www.nature.com/sdata/research-articles",
    "Nature Scientific Reports": "https://www.nature.com/srep/research-articles",
    "Nature Signal Transduction and Targeted Therapy": "https://www.nature.com/sigtrans/research-articles",
    "Nature Spinal Cord": "https://www.nature.com/sc/research-articles",
    "Nature Spinal Cord Series and Cases": "https://www.nature.com/scsandc/research-articles",
    "Nature Translational Psychiatry": "https://www.nature.com/tp/research-articles",
}
