from datetime import datetime
from time import mktime
from typing import List

import feedparser
from feedparser import FeedParserDict
from pandas import DataFrame

RSS_FEEDS: dict[str, str] = {
    "Nature Acta Pharmacologica Sinica": "https://www.nature.com/aps.rss",
    "Nature BDJ In Practice": "https://www.nature.com/bdjinpractice.rss",
    "Nature BDJ Open": "https://www.nature.com/bdjopen.rss",
    "Nature BDJ Student": "https://www.nature.com/bdjstudent.rss",
    "Nature BDJ Team": "https://www.nature.com/bdjteam.rss",
    "Nature Biopharma Dealmakers": "https://www.nature.com/biopharmdeal.rss",
    "Nature BJC Reports": "https://www.nature.com/bjcreports.rss",
    "Nature Blood Cancer Journal": "https://www.nature.com/bcj.rss",
    "Nature Bone Marrow Transplantation": "https://www.nature.com/bmt.rss",
    "Nature Bone Research": "https://www.nature.com/boneres.rss",
    "Nature British Dental Journal": "https://www.nature.com/bdj.rss",
    "Nature British Journal of Cancer": "https://www.nature.com/bjc.rss",
    "Nature Cancer Gene Therapy": "https://www.nature.com/cgt.rss",
    "Nature Cell Death & Differentiation": "https://www.nature.com/cdd.rss",
    "Nature Cell Death & Disease": "https://www.nature.com/cddis.rss",
    "Nature Cell Death Discovery": "https://www.nature.com/cddiscovery.rss",
    "Nature Cell Discovery": "https://www.nature.com/celldisc.rss",
    "Nature Cell Research": "https://www.nature.com/cr.rss",
    "Nature Cellular & Molecular Immunology": "https://www.nature.com/cmi.rss",
    "Nature Communications Biology": "https://www.nature.com/commsbio.rss",
    "Nature Communications Chemistry": "https://www.nature.com/commschem.rss",
    "Nature Communications Earth & Environment": "https://www.nature.com/commsenv.rss",
    "Nature Communications Engineering": "https://www.nature.com/commseng.rss",
    "Nature Communications Materials": "https://www.nature.com/commsmat.rss",
    "Nature Communications Medicine": "https://www.nature.com/commsmed.rss",
    "Nature Communications Physics": "https://www.nature.com/commsphys.rss",
    "Nature Communications Psychology": "https://www.nature.com/commspsychol.rss",
    "Nature European Journal of Clinical Nutrition": "https://www.nature.com/ejcn.rss",
    "Nature European Journal of Human Genetics": "https://www.nature.com/ejhg.rss",
    "Nature Evidence-Based Dentistry": "https://www.nature.com/ebd.rss",
    "Nature Experimental & Molecular Medicine": "https://www.nature.com/emm.rss",
    "Nature Eye": "https://www.nature.com/eye.rss",
    "Nature Gene Therapy": "https://www.nature.com/gt.rss",
    "Nature Genes & Immunity": "https://www.nature.com/gene.rss",
    "Nature Heredity": "https://www.nature.com/hdy.rss",
    "Nature Human Genome Variation": "https://www.nature.com/hgv.rss",
    "Nature Humanities and Social Sciences Communications": "https://www.nature.com/palcomms.rss",
    "Nature Hypertension Research": "https://www.nature.com/hr.rss",
    "Nature International Journal of Impotence Research": "https://www.nature.com/ijir.rss",
    "Nature International Journal of Obesity": "https://www.nature.com/ijo.rss",
    "Nature International Journal of Obesity Supplements": "https://www.nature.com/ijosup.rss",
    "Nature International Journal of Oral Science": "https://www.nature.com/ijos.rss",
    "Nature ISME Communications": "https://www.nature.com/ismecomms.rss",
    "Nature The ISME Journal": "https://www.nature.com/ismej.rss",
    "Nature The Journal of Antibiotics": "https://www.nature.com/ja.rss",
    "Nature Journal of Exposure Science & Environmental Epidemiology": "https://www.nature.com/jes.rss",
    "Nature Journal of Human Genetics": "https://www.nature.com/jhg.rss",
    "Nature Journal of Human Hypertension": "https://www.nature.com/jhh.rss",
    "Nature Journal of Perinatology": "https://www.nature.com/jp.rss",
    "Nature Lab Animal": "https://www.nature.com/laban.rss",
    "Nature Laboratory Investigation": "https://www.nature.com/labinvest.rss",
    "Nature Leukemia": "https://www.nature.com/leu.rss",
    "Nature Leukemia Supplements": "https://www.nature.com/leusup.rss",
    "Nature Light: Science & Applications": "https://www.nature.com/lsa.rss",
    "Nature Microsystems & Nanoengineering": "https://www.nature.com/micronano.rss",
    "Nature Modern Pathology": "https://www.nature.com/modpathol.rss",
    "Nature Molecular Psychiatry": "https://www.nature.com/mp.rss",
    "Nature Mucosal Immunology": "https://www.nature.com/mi.rss",
    "Nature": "https://www.nature.com/nature.rss",
    "Nature Africa": "https://www.nature.com/natafrica.rss",
    "Nature Aging": "https://www.nature.com/nataging.rss",
    "Nature Astronomy": "https://www.nature.com/natastron.rss",
    "Nature Biomedical Engineering": "https://www.nature.com/natbiomedeng.rss",
    "Nature Biotechnology": "https://www.nature.com/nbt.rss",
    "Nature Cancer": "https://www.nature.com/natcancer.rss",
    "Nature Cardiovascular Research": "https://www.nature.com/natcardiovascres.rss",
    "Nature Catalysis": "https://www.nature.com/natcatal.rss",
    "Nature Cell Biology": "https://www.nature.com/ncb.rss",
    "Nature Chemical Biology": "https://www.nature.com/nchembio.rss",
    "Nature Chemical Engineering": "https://www.nature.com/natchemeng.rss",
    "Nature Chemistry": "https://www.nature.com/nchem.rss",
    "Nature Cities": "https://www.nature.com/natcities.rss",
    "Nature Climate Change": "https://www.nature.com/nclimate.rss",
    "Nature Communications": "https://www.nature.com/ncomms.rss",
    "Nature Computational Science": "https://www.nature.com/natcomputsci.rss",
    "Nature Digest": "https://www.nature.com/ndigest.rss",
    "Nature Ecology & Evolution": "https://www.nature.com/natecolevol.rss",
    "Nature Electronics": "https://www.nature.com/natelectron.rss",
    "Nature Energy": "https://www.nature.com/nenergy.rss",
    "Nature Food": "https://www.nature.com/natfood.rss",
    "Nature Genetics": "https://www.nature.com/ng.rss",
    "Nature Geoscience": "https://www.nature.com/ngeo.rss",
    "Nature Human Behaviour": "https://www.nature.com/nathumbehav.rss",
    "Nature Immunology": "https://www.nature.com/ni.rss",
    "Nature India": "https://www.nature.com/natindia.rss",
    "Nature Italy": "https://www.nature.com/natitaly.rss",
    "Nature Machine Intelligence": "https://www.nature.com/natmachintell.rss",
    "Nature Materials": "https://www.nature.com/nmat.rss",
    "Nature Medicine": "https://www.nature.com/nm.rss",
    "Nature Mental Health": "https://www.nature.com/natmentalhealth.rss",
    "Nature Metabolism": "https://www.nature.com/natmetab.rss",
    "Nature Methods": "https://www.nature.com/nmeth.rss",
    "Nature Microbiology": "https://www.nature.com/nmicrobiol.rss",
    "Nature Nanotechnology": "https://www.nature.com/nnano.rss",
    "Nature Neuroscience": "https://www.nature.com/neuro.rss",
    "Nature Photonics": "https://www.nature.com/nphoton.rss",
    "Nature Physics": "https://www.nature.com/nphys.rss",
    "Nature Plants": "https://www.nature.com/nplants.rss",
    "Nature Protocols": "https://www.nature.com/nprot.rss",
    "Nature Reviews Bioengineering": "https://www.nature.com/natrevbioeng.rss",
    "Nature Reviews Cancer": "https://www.nature.com/nrc.rss",
    "Nature Reviews Cardiology": "https://www.nature.com/nrcardio.rss",
    "Nature Reviews Chemistry": "https://www.nature.com/natrevchem.rss",
    "Nature Reviews Clean Technology": "https://www.nature.com/nrct.rss",
    "Nature Reviews Clinical Oncology": "https://www.nature.com/nrclinonc.rss",
    "Nature Reviews Disease Primers": "https://www.nature.com/nrdp.rss",
    "Nature Reviews Drug Discovery": "https://www.nature.com/nrd.rss",
    "Nature Reviews Earth & Environment": "https://www.nature.com/natrevearthenviron.rss",
    "Nature Reviews Electrical Engineering": "https://www.nature.com/natrevelectreng.rss",
    "Nature Reviews Endocrinology": "https://www.nature.com/nrendo.rss",
    "Nature Reviews Gastroenterology & Hepatology": "https://www.nature.com/nrgastro.rss",
    "Nature Reviews Genetics": "https://www.nature.com/nrg.rss",
    "Nature Reviews Immunology": "https://www.nature.com/nri.rss",
    "Nature Reviews Materials": "https://www.nature.com/natrevmats.rss",
    "Nature Reviews Methods Primers": "https://www.nature.com/nrmp.rss",
    "Nature Reviews Microbiology": "https://www.nature.com/nrmicro.rss",
    "Nature Reviews Molecular Cell Biology": "https://www.nature.com/nrm.rss",
    "Nature Reviews Nephrology": "https://www.nature.com/nrneph.rss",
    "Nature Reviews Neurology": "https://www.nature.com/nrneurol.rss",
    "Nature Reviews Neuroscience": "https://www.nature.com/nrn.rss",
    "Nature Reviews Physics": "https://www.nature.com/natrevphys.rss",
    "Nature Reviews Psychology": "https://www.nature.com/nrpsychol.rss",
    "Nature Reviews Rheumatology": "https://www.nature.com/nrrheum.rss",
    "Nature Reviews Urology": "https://www.nature.com/nrurol.rss",
    "Nature Structural & Molecular Biology": "https://www.nature.com/nsmb.rss",
    "Nature Sustainability": "https://www.nature.com/natsustain.rss",
    "Nature Synthesis": "https://www.nature.com/natsynth.rss",
    "Nature Water": "https://www.nature.com/natwater.rss",
    "Nature Neuropsychopharmacology": "https://www.nature.com/npp.rss",
    "Nature NPG Asia Materials": "https://www.nature.com/am.rss",
    "Nature npj 2D Materials and Applications": "https://www.nature.com/npj2dmaterials.rss",
    "Nature npj Advanced Manufacturing": "https://www.nature.com/npjadvmanuf.rss",
    "Nature npj Aging": "https://www.nature.com/npjamd.rss",
    "Nature npj Antimicrobials and Resistance": "https://www.nature.com/npjamar.rss",
    "Nature npj Biodiversity": "https://www.nature.com/npjbiodivers.rss",
    "Nature npj Biofilms and Microbiomes": "https://www.nature.com/npjbiofilms.rss",
    "Nature npj Biological Physics and Mechanics": "https://www.nature.com/npjbiolphysmech.rss",
    "Nature npj Biological Timing and Sleep": "https://www.nature.com/npjbts.rss",
    "Nature npj Biosensing": "https://www.nature.com/npjbiosensing.rss",
    "Nature npj Breast Cancer": "https://www.nature.com/npjbcancer.rss",
    "Nature npj Cardiovascular Health": "https://www.nature.com/npjcardiohealth.rss",
    "Nature npj Clean Water": "https://www.nature.com/npjcleanwater.rss",
    "Nature npj Climate Action": "https://www.nature.com/npjclimataction.rss",
    "Nature npj Climate and Atmospheric Science": "https://www.nature.com/npjclimatsci.rss",
    "Nature npj Complexity": "https://www.nature.com/npjcomplex.rss",
    "Nature npj Computational Materials": "https://www.nature.com/npjcompumats.rss",
    "Nature npj Digital Medicine": "https://www.nature.com/npjdigitalmed.rss",
    "Nature npj Flexible Electronics": "https://www.nature.com/npjflexelectron.rss",
    "Nature npj Genomic Medicine": "https://www.nature.com/npjgenmed.rss",
    "Nature npj Gut and Liver": "https://www.nature.com/npjgutliver.rss",
    "Nature npj Imaging": "https://www.nature.com/npjimaging.rss",
    "Nature npj Materials Degradation": "https://www.nature.com/npjmatdeg.rss",
    "Nature npj Materials Sustainability": "https://www.nature.com/npjmatsustain.rss",
    "Nature npj Mental Health Research": "https://www.nature.com/npjmentalhealth.rss",
    "Nature npj Metabolic Health and Disease": "https://www.nature.com/npjmetabhealth.rss",
    "Nature npj Microgravity": "https://www.nature.com/npjmgrav.rss",
    "Nature npj Nanophotonics": "https://www.nature.com/npjnanophoton.rss",
    "Nature npj Natural Hazards": "https://www.nature.com/npjnathazards.rss",
    "Nature npj Ocean Sustainability": "https://www.nature.com/npjoceansustain.rss",
    "Nature npj Parkinson's Disease": "https://www.nature.com/npjparkd.rss",
    "Nature npj Precision Oncology": "https://www.nature.com/npjprecisiononcology.rss",
    "Nature npj Primary Care Respiratory Medicine": "https://www.nature.com/npjpcrm.rss",
    "Nature npj Quantum Information": "https://www.nature.com/npjqi.rss",
    "Nature npj Quantum Materials": "https://www.nature.com/npjquantmats.rss",
    "Nature npj Regenerative Medicine": "https://www.nature.com/npjregenmed.rss",
    "Nature npj Robotics": "https://www.nature.com/npjrobot.rss",
    "Nature npj Science of Food": "https://www.nature.com/npjscifood.rss",
    "Nature npj Science of Learning": "https://www.nature.com/npjscilearn.rss",
    "Nature npj Spintronics": "https://www.nature.com/npjspintronics.rss",
    "Nature npj Sustainable Agriculture": "https://www.nature.com/npjsustainagric.rss",
    "Nature npj Sustainable Mobility and Transport": "https://www.nature.com/npjsustainmobil.rss",
    "Nature npj Systems Biology and Applications": "https://www.nature.com/npjsba.rss",
    "Nature npj Unconventional Computing": "https://www.nature.com/npjunconvcomput.rss",
    "Nature npj Urban Sustainability": "https://www.nature.com/npjurbansustain.rss",
    "Nature npj Vaccines": "https://www.nature.com/npjvaccines.rss",
    "Nature npj Viruses": "https://www.nature.com/npjviruses.rss",
    "Nature npj Women's Health": "https://www.nature.com/npjwomenshealth.rss",
    "Nature NPP-Psychiatry and Neuroscience": "https://www.nature.com/dpn.rss",
    "Nature Nutrition & Diabetes": "https://www.nature.com/nutd.rss",
    "Nature Oncogene": "https://www.nature.com/onc.rss",
    "Nature Oncogenesis": "https://www.nature.com/oncsis.rss",
    "Nature Pediatric Research": "https://www.nature.com/pr.rss",
    "Nature The Pharmacogenomics Journal": "https://www.nature.com/tpj.rss",
    "Nature Polymer Journal": "https://www.nature.com/pj.rss",
    "Nature Prostate Cancer and Prostatic Diseases": "https://www.nature.com/pcan.rss",
    "Nature Schizophrenia": "https://www.nature.com/npjschz.rss",
    "Nature Scientific American": "https://www.nature.com/scientificamerican.rss",
    "Nature Scientific American Mind": "https://www.nature.com/scientificamericanmind.rss",
    "Nature Scientific Data": "https://www.nature.com/sdata.rss",
    "Nature Scientific Reports": "https://www.nature.com/srep.rss",
    "Nature Signal Transduction and Targeted Therapy": "https://www.nature.com/sigtrans.rss",
    "Nature Spinal Cord": "https://www.nature.com/sc.rss",
    "Nature Spinal Cord Series and Cases": "https://www.nature.com/scsandc.rss",
    "Nature Translational Psychiatry": "https://www.nature.com/tp.rss",
}


def getRSSFeed(feedURL: str) -> FeedParserDict:
    return feedparser.parse(url_file_stream_or_string=feedURL)


def parseFeed(feed: FeedParserDict) -> DataFrame:
    data: dict[str, List[str | datetime]] = {
        "doi": [],
        "url": [],
        "title": [],
        "journal": [],
        "updated": [],
        "added": [],
    }

    entries: List[dict] = feed["entries"]

    entry: dict
    for entry in entries:
        data["doi"].append(entry["prism_doi"])
        data["url"].append(entry["prism_url"])
        data["title"].append(entry["title"])
        data["journal"].append(entry["prism_publicationname"])
        data["updated"].append(datetime.fromtimestamp(mktime(entry["updated_parsed"])))
        data["added"].append(datetime.now())

    return DataFrame(data=data)
