RSS_FEEDS: dict[str, str] = {
    "Frontiers in Acoustics": "https://www.frontiersin.org/journals/acoustics/rss",
    "Acta Biochimica Polonica": "https://www.frontiersin.org/journals/acta-biochimica-polonica/rss",
    "Acta Virologica": "https://www.frontiersin.org/journals/acta-virologica/rss",
    "Frontiers in Adolescent Medicine": "https://www.frontiersin.org/journals/adolescent-medicine/rss",
    "Advanced Optical Technologies": "https://www.frontiersin.org/journals/advanced-optical-technologies/rss",
    "Advances in Drug and Alcohol Research": "https://www.frontiersin.org/journals/advances-in-drug-and-alcohol-research/rss",
    "Frontiers in Aerospace Engineering": "https://www.frontiersin.org/journals/aerospace-engineering/rss",
    "Aerospace Research Communications": "https://www.frontiersin.org/journals/aerospace-research-communications/rss",
    "Frontiers in Aging": "https://www.frontiersin.org/journals/aging/rss",
    "Frontiers in Aging Neuroscience": "https://www.frontiersin.org/journals/aging-neuroscience/rss",
    "Frontiers in Agronomy": "https://www.frontiersin.org/journals/agronomy/rss",
    "Frontiers in Allergy": "https://www.frontiersin.org/journals/allergy/rss",
    "Frontiers in Amphibian and Reptile Science": "https://www.frontiersin.org/journals/amphibian-and-reptile-science/rss",
    "Frontiers in Analytical Science": "https://www.frontiersin.org/journals/analytical-science/rss",
    "Frontiers in Anesthesiology": "https://www.frontiersin.org/journals/anesthesiology/rss",
    "Frontiers in Animal Science": "https://www.frontiersin.org/journals/animal-science/rss",
    "Frontiers in Antennas and Propagation": "https://www.frontiersin.org/journals/antennas-and-propagation/rss",
    "Frontiers in Antibiotics": "https://www.frontiersin.org/journals/antibiotics/rss",
    "Frontiers in Applied Mathematics and Statistics": "https://www.frontiersin.org/journals/applied-mathematics-and-statistics/rss",
    "Frontiers in Aquaculture": "https://www.frontiersin.org/journals/aquaculture/rss",
    "Frontiers in Arachnid Science": "https://www.frontiersin.org/journals/arachnid-science/rss",
    "Frontiers in Artificial Intelligence": "https://www.frontiersin.org/journals/artificial-intelligence/rss",
    "Frontiers in Astronomy and Space Sciences": "https://www.frontiersin.org/journals/astronomy-and-space-sciences/rss",
    "Frontiers in Audiology and Otology": "https://www.frontiersin.org/journals/audiology-and-otology/rss",
    "Frontiers in Bacteriology": "https://www.frontiersin.org/journals/bacteriology/rss",
    "Frontiers in Batteries and Electrochemistry": "https://www.frontiersin.org/journals/batteries-and-electrochemistry/rss",
    "Frontiers in Bee Science": "https://www.frontiersin.org/journals/bee-science/rss",
    "Frontiers in Behavioral Economics": "https://www.frontiersin.org/journals/behavioral-economics/rss",
    "Frontiers in Behavioral Neuroscience": "https://www.frontiersin.org/journals/behavioral-neuroscience/rss",
    "Frontiers in Big Data": "https://www.frontiersin.org/journals/big-data/rss",
    "Frontiers in Bioengineering and Biotechnology": "https://www.frontiersin.org/journals/bioengineering-and-biotechnology/rss",
    "Frontiers in Bioinformatics": "https://www.frontiersin.org/journals/bioinformatics/rss",
    "Frontiers in Biomaterials Science": "https://www.frontiersin.org/journals/biomaterials-science/rss",
    "Frontiers in Biophysics": "https://www.frontiersin.org/journals/biophysics/rss",
    "Frontiers in Bird Science": "https://www.frontiersin.org/journals/bird-science/rss",
    "Frontiers in Blockchain": "https://www.frontiersin.org/journals/blockchain/rss",
    "British Journal of Biomedical Science": "https://www.frontiersin.org/journals/british-journal-of-biomedical-science/rss",
    "Frontiers in Built Environment": "https://www.frontiersin.org/journals/built-environment/rss",
    "Frontiers in Cancer Control and Society": "https://www.frontiersin.org/journals/cancer-control-and-society/rss",
    "Frontiers in Carbon": "https://www.frontiersin.org/journals/carbon/rss",
    "Frontiers in Cardiovascular Medicine": "https://www.frontiersin.org/journals/cardiovascular-medicine/rss",
    "Frontiers in Catalysis": "https://www.frontiersin.org/journals/catalysis/rss",
    "Frontiers in Cell and Developmental Biology": "https://www.frontiersin.org/journals/cell-and-developmental-biology/rss",
    "Frontiers in Cell Death": "https://www.frontiersin.org/journals/cell-death/rss",
    "Frontiers in Cellular and Infection Microbiology": "https://www.frontiersin.org/journals/cellular-and-infection-microbiology/rss",
    "Frontiers in Cellular Neuroscience": "https://www.frontiersin.org/journals/cellular-neuroscience/rss",
    "Frontiers in Ceramics": "https://www.frontiersin.org/journals/ceramics/rss",
    "Frontiers in Chemical Biology": "https://www.frontiersin.org/journals/chemical-biology/rss",
    "Frontiers in Chemical Engineering": "https://www.frontiersin.org/journals/chemical-engineering/rss",
    "Frontiers in Chemistry": "https://www.frontiersin.org/journals/chemistry/rss",
    "Frontiers in Child and Adolescent Psychiatry": "https://www.frontiersin.org/journals/child-and-adolescent-psychiatry/rss",
    "Frontiers in Climate": "https://www.frontiersin.org/journals/climate/rss",
    "Frontiers in Clinical Diabetes and Healthcare": "https://www.frontiersin.org/journals/clinical-diabetes-and-healthcare/rss",
    "Frontiers in Coatings, Dyes and Interface Engineering": "https://www.frontiersin.org/journals/coatings-dyes-and-interface-engineering/rss",
    "Frontiers in Cognition": "https://www.frontiersin.org/journals/cognition/rss",
    "Frontiers in Communication": "https://www.frontiersin.org/journals/communication/rss",
    "Frontiers in Communications and Networks": "https://www.frontiersin.org/journals/communications-and-networks/rss",
    "Frontiers in Complex Systems": "https://www.frontiersin.org/journals/complex-systems/rss",
    "Frontiers in Computational Neuroscience": "https://www.frontiersin.org/journals/computational-neuroscience/rss",
    "Frontiers in Computer Science": "https://www.frontiersin.org/journals/computer-science/rss",
    "Frontiers in Conservation Science": "https://www.frontiersin.org/journals/conservation-science/rss",
    "Frontiers in Control Engineering": "https://www.frontiersin.org/journals/control-engineering/rss",
    "Frontiers in Dementia": "https://www.frontiersin.org/journals/dementia/rss",
    "Frontiers in Dental Medicine": "https://www.frontiersin.org/journals/dental-medicine/rss",
    "Frontiers in Detector Science and Technology": "https://www.frontiersin.org/journals/detector-science-and-technology/rss",
    "Frontiers in Developmental Psychology": "https://www.frontiersin.org/journals/developmental-psychology/rss",
    "Frontiers in Digital Health": "https://www.frontiersin.org/journals/digital-health/rss",
    "Frontiers in Digital Humanities": "https://www.frontiersin.org/journals/digital-humanities/rss",
    "Frontiers in Disaster and Emergency Medicine": "https://www.frontiersin.org/journals/disaster-and-emergency-medicine/rss",
    "Frontiers in Drug Delivery": "https://www.frontiersin.org/journals/drug-delivery/rss",
    "Frontiers in Drug Discovery": "https://www.frontiersin.org/journals/drug-discovery/rss",
    "Frontiers in Drug Safety and Regulation": "https://www.frontiersin.org/journals/drug-safety-and-regulation/rss",
    "Dystonia": "https://www.frontiersin.org/journals/dystonia/rss",
    "Frontiers in Earth Science": "https://www.frontiersin.org/journals/earth-science/rss",
    "Earth Science, Systems and Society": "https://www.frontiersin.org/journals/earth-science-systems-and-society/rss",
    "Frontiers in Ecology and Evolution": "https://www.frontiersin.org/journals/ecology-and-evolution/rss",
    "Frontiers in Education": "https://www.frontiersin.org/journals/education/rss",
    "Frontiers in Electronic Materials": "https://www.frontiersin.org/journals/electronic-materials/rss",
    "Frontiers in Electronics": "https://www.frontiersin.org/journals/electronics/rss",
    "Frontiers in Endocrinology": "https://www.frontiersin.org/journals/endocrinology/rss",
    "Frontiers in Energy Efficiency": "https://www.frontiersin.org/journals/energy-efficiency/rss",
    "Frontiers in Energy Research": "https://www.frontiersin.org/journals/energy-research/rss",
    "Frontiers in Environmental Archaeology": "https://www.frontiersin.org/journals/environmental-archaeology/rss",
    "Frontiers in Environmental Chemistry": "https://www.frontiersin.org/journals/environmental-chemistry/rss",
    "Frontiers in Environmental Economics": "https://www.frontiersin.org/journals/environmental-economics/rss",
    "Frontiers in Environmental Engineering": "https://www.frontiersin.org/journals/environmental-engineering/rss",
    "Frontiers in Environmental Health": "https://www.frontiersin.org/journals/environmental-health/rss",
    "Frontiers in Environmental Science": "https://www.frontiersin.org/journals/environmental-science/rss",
    "Frontiers in Epidemiology": "https://www.frontiersin.org/journals/epidemiology/rss",
    "Frontiers in Epigenetics and Epigenomics": "https://www.frontiersin.org/journals/epigenetics-and-epigenomics/rss",
    "Frontiers in Ethology": "https://www.frontiersin.org/journals/ethology/rss",
    "European Journal of Cultural Management and Policy": "https://www.frontiersin.org/journals/european-journal-of-cultural-management-and-policy/rss",
    "Frontiers in Evolutionary Neuroscience": "https://www.frontiersin.org/journals/evolutionary-neuroscience/rss",
    "Experimental Biology and Medicine": "https://www.frontiersin.org/journals/experimental-biology-and-medicine/rss",
    "Frontiers in Fish Science": "https://www.frontiersin.org/journals/fish-science/rss",
    "Frontiers in Food Science and Technology": "https://www.frontiersin.org/journals/food-science-and-technology/rss",
    "Frontiers in Forests and Global Change": "https://www.frontiersin.org/journals/forests-and-global-change/rss",
    "Frontiers in Freshwater Science": "https://www.frontiersin.org/journals/freshwater-science/rss",
    "Frontiers in Fuels": "https://www.frontiersin.org/journals/fuels/rss",
    "Frontiers in Fungal Biology": "https://www.frontiersin.org/journals/fungal-biology/rss",
    "Frontiers in Future Transportation": "https://www.frontiersin.org/journals/future-transportation/rss",
    "Frontiers in Gastroenterology": "https://www.frontiersin.org/journals/gastroenterology/rss",
    "Frontiers in Genetics": "https://www.frontiersin.org/journals/genetics/rss",
    "Frontiers in Genome Editing": "https://www.frontiersin.org/journals/genome-editing/rss",
    "Frontiers in Geochemistry": "https://www.frontiersin.org/journals/geochemistry/rss",
    "Frontiers in Global Women's Health": "https://www.frontiersin.org/journals/global-womens-health/rss",
    "Frontiers in Health Services": "https://www.frontiersin.org/journals/health-services/rss",
    "Frontiers in Hematology": "https://www.frontiersin.org/journals/hematology/rss",
    "Frontiers in High Performance Computing": "https://www.frontiersin.org/journals/high-performance-computing/rss",
    "Frontiers in Horticulture": "https://www.frontiersin.org/journals/horticulture/rss",
    "Frontiers in Human Dynamics": "https://www.frontiersin.org/journals/human-dynamics/rss",
    "Frontiers in Human Neuroscience": "https://www.frontiersin.org/journals/human-neuroscience/rss",
    "Frontiers in ICT": "https://www.frontiersin.org/journals/ict/rss",
    "Frontiers in Imaging": "https://www.frontiersin.org/journals/imaging/rss",
    "Frontiers in Immunology": "https://www.frontiersin.org/journals/immunology/rss",
    "Frontiers in Industrial Engineering": "https://www.frontiersin.org/journals/industrial-engineering/rss",
    "Frontiers in Industrial Microbiology": "https://www.frontiersin.org/journals/industrial-microbiology/rss",
    "Frontiers in Insect Science": "https://www.frontiersin.org/journals/insect-science/rss",
    "Frontiers in Integrative Neuroscience": "https://www.frontiersin.org/journals/integrative-neuroscience/rss",
    "International Journal of Public Health": "https://www.frontiersin.org/journals/international-journal-of-public-health/rss",
    "Journal of Abdominal Wall Surgery": "https://www.frontiersin.org/journals/journal-of-abdominal-wall-surgery/rss",
    "Journal of Cutaneous Immunology and Allergy": "https://www.frontiersin.org/journals/journal-of-cutaneous-immunology-and-allergy/rss",
    "Journal of Pharmacy & Pharmaceutical Sciences": "https://www.frontiersin.org/journals/journal-of-pharmacy-pharmaceutical-sciences/rss",
    "Frontiers in Lab on a Chip Technologies": "https://www.frontiersin.org/journals/lab-on-a-chip-technologies/rss",
    "Frontiers in Language Sciences": "https://www.frontiersin.org/journals/language-sciences/rss",
    "Frontiers in Lupus": "https://www.frontiersin.org/journals/lupus/rss",
    "Frontiers in Malaria": "https://www.frontiersin.org/journals/malaria/rss",
    "Frontiers in Mammal Science": "https://www.frontiersin.org/journals/mammal-science/rss",
    "Frontiers in Manufacturing Technology": "https://www.frontiersin.org/journals/manufacturing-technology/rss",
    "Frontiers in Marine Science": "https://www.frontiersin.org/journals/marine-science/rss",
    "Frontiers in Materials": "https://www.frontiersin.org/journals/materials/rss",
    "Frontiers in Mechanical Engineering": "https://www.frontiersin.org/journals/mechanical-engineering/rss",
    "Frontiers in Medical Engineering": "https://www.frontiersin.org/journals/medical-engineering/rss",
    "Frontiers in Medical Technology": "https://www.frontiersin.org/journals/medical-technology/rss",
    "Frontiers in Medicine": "https://www.frontiersin.org/journals/medicine/rss",
    "Frontiers in Membrane Science and Technology": "https://www.frontiersin.org/journals/membrane-science-and-technology/rss",
    "Frontiers in Metals and Alloys": "https://www.frontiersin.org/journals/metals-and-alloys/rss",
    "Frontiers in Microbiology": "https://www.frontiersin.org/journals/microbiology/rss",
    "Frontiers in Microbiomes": "https://www.frontiersin.org/journals/microbiomes/rss",
    "Frontiers in Molecular Biosciences": "https://www.frontiersin.org/journals/molecular-biosciences/rss",
    "Frontiers in Molecular Medicine": "https://www.frontiersin.org/journals/molecular-medicine/rss",
    "Frontiers in Molecular Neuroscience": "https://www.frontiersin.org/journals/molecular-neuroscience/rss",
    "Frontiers in Musculoskeletal Disorders": "https://www.frontiersin.org/journals/musculoskeletal-disorders/rss",
    "Frontiers in Nanotechnology": "https://www.frontiersin.org/journals/nanotechnology/rss",
    "Frontiers in Natural Products": "https://www.frontiersin.org/journals/natural-products/rss",
    "Frontiers in Nephrology": "https://www.frontiersin.org/journals/nephrology/rss",
    "Frontiers in Network Physiology": "https://www.frontiersin.org/journals/network-physiology/rss",
    "Frontiers in Neural Circuits": "https://www.frontiersin.org/journals/neural-circuits/rss",
    "Frontiers in Neuroanatomy": "https://www.frontiersin.org/journals/neuroanatomy/rss",
    "Frontiers in Neuroenergetics": "https://www.frontiersin.org/journals/neuroenergetics/rss",
    "Frontiers in Neuroengineering": "https://www.frontiersin.org/journals/neuroengineering/rss",
    "Frontiers in Neuroergonomics": "https://www.frontiersin.org/journals/neuroergonomics/rss",
    "Frontiers in Neuroimaging": "https://www.frontiersin.org/journals/neuroimaging/rss",
    "Frontiers in Neuroinformatics": "https://www.frontiersin.org/journals/neuroinformatics/rss",
    "Frontiers in Neurology": "https://www.frontiersin.org/journals/neurology/rss",
    "Frontiers in Neurorobotics": "https://www.frontiersin.org/journals/neurorobotics/rss",
    "Frontiers in Neuroscience": "https://www.frontiersin.org/journals/neuroscience/rss",
    "Frontiers in Nuclear Engineering": "https://www.frontiersin.org/journals/nuclear-engineering/rss",
    "Frontiers in Nuclear Medicine": "https://www.frontiersin.org/journals/nuclear-medicine/rss",
    "Frontiers in Nutrition": "https://www.frontiersin.org/journals/nutrition/rss",
    "Frontiers in Ocean Sustainability": "https://www.frontiersin.org/journals/ocean-sustainability/rss",
    "Frontiers in Oncology": "https://www.frontiersin.org/journals/oncology/rss",
    "Frontiers in Oncology Reviews Partnerships": "https://www.frontiersin.org/journals/oncology-reviews-partnerships/rss",
    "Frontiers in Ophthalmology": "https://www.frontiersin.org/journals/ophthalmology/rss",
    "Frontiers in Oral Health": "https://www.frontiersin.org/journals/oral-health/rss",
    "Frontiers in Organizational Psychology": "https://www.frontiersin.org/journals/organizational-psychology/rss",
    "Frontiers in Pain Research": "https://www.frontiersin.org/journals/pain-research/rss",
    "Frontiers in Parasitology": "https://www.frontiersin.org/journals/parasitology/rss",
    "Pastoralism: Research, Policy and Practice": "https://www.frontiersin.org/journals/pastoralism-research-policy-and-practice/rss",
    "Pathology and Oncology Research": "https://www.frontiersin.org/journals/pathology-and-oncology-research/rss",
    "Frontiers in Pediatrics": "https://www.frontiersin.org/journals/pediatrics/rss",
    "Frontiers in Pharmacology": "https://www.frontiersin.org/journals/pharmacology/rss",
    "Frontiers in Photobiology": "https://www.frontiersin.org/journals/photobiology/rss",
    "Frontiers in Photonics": "https://www.frontiersin.org/journals/photonics/rss",
    "Frontiers in Physics": "https://www.frontiersin.org/journals/physics/rss",
    "Frontiers in Physiology": "https://www.frontiersin.org/journals/physiology/rss",
    "Frontiers in Plant Physiology": "https://www.frontiersin.org/journals/plant-physiology/rss",
    "Frontiers in Plant Science": "https://www.frontiersin.org/journals/plant-science/rss",
    "Frontiers in Political Science": "https://www.frontiersin.org/journals/political-science/rss",
    "Frontiers in Protistology": "https://www.frontiersin.org/journals/protistology/rss",
    "Frontiers in Psychiatry": "https://www.frontiersin.org/journals/psychiatry/rss",
    "Frontiers in Psychology": "https://www.frontiersin.org/journals/psychology/rss",
    "Frontiers in Public Health": "https://www.frontiersin.org/journals/public-health/rss",
    "Public Health Reviews": "https://www.frontiersin.org/journals/public-health-reviews/rss",
    "Frontiers in Quantum Science and Technology": "https://www.frontiersin.org/journals/quantum-science-and-technology/rss",
    "Frontiers in Radiology": "https://www.frontiersin.org/journals/radiology/rss",
    "Frontiers in Rehabilitation Sciences": "https://www.frontiersin.org/journals/rehabilitation-sciences/rss",
    "Frontiers in Remote Sensing": "https://www.frontiersin.org/journals/remote-sensing/rss",
    "Frontiers in Reproductive Health": "https://www.frontiersin.org/journals/reproductive-health/rss",
    "Frontiers in Research Metrics and Analytics": "https://www.frontiersin.org/journals/research-metrics-and-analytics/rss",
    "Frontiers in RNA Research": "https://www.frontiersin.org/journals/rna-research/rss",
    "Frontiers in Robotics and AI": "https://www.frontiersin.org/journals/robotics-and-ai/rss",
    "Frontiers in Science": "https://www.frontiersin.org/journals/science/rss",
    "Frontiers in Sensors": "https://www.frontiersin.org/journals/sensors/rss",
    "Frontiers in Signal Processing": "https://www.frontiersin.org/journals/signal-processing/rss",
    "Frontiers in Sleep": "https://www.frontiersin.org/journals/sleep/rss",
    "Frontiers in Smart Grids": "https://www.frontiersin.org/journals/smart-grids/rss",
    "Frontiers in Social Psychology": "https://www.frontiersin.org/journals/social-psychology/rss",
    "Frontiers in Society Journal Archive": "https://www.frontiersin.org/journals/society-journal-archive/rss",
    "Frontiers in Sociology": "https://www.frontiersin.org/journals/sociology/rss",
    "Frontiers in Soft Matter": "https://www.frontiersin.org/journals/soft-matter/rss",
    "Frontiers in Soil Science": "https://www.frontiersin.org/journals/soil-science/rss",
    "Frontiers in Space Technologies": "https://www.frontiersin.org/journals/space-technologies/rss",
    "Spanish Journal of Soil Science": "https://www.frontiersin.org/journals/spanish-journal-of-soil-science/rss",
    "Frontiers in Sports and Active Living": "https://www.frontiersin.org/journals/sports-and-active-living/rss",
    "Frontiers in Stroke": "https://www.frontiersin.org/journals/stroke/rss",
    "Frontiers in Surgery": "https://www.frontiersin.org/journals/surgery/rss",
    "Frontiers in Sustainability": "https://www.frontiersin.org/journals/sustainability/rss",
    "Frontiers in Sustainable Cities": "https://www.frontiersin.org/journals/sustainable-cities/rss",
    "Frontiers in Sustainable Energy Policy": "https://www.frontiersin.org/journals/sustainable-energy-policy/rss",
    "Frontiers in Sustainable Food Systems": "https://www.frontiersin.org/journals/sustainable-food-systems/rss",
    "Frontiers in Sustainable Resource Management": "https://www.frontiersin.org/journals/sustainable-resource-management/rss",
    "Frontiers in Sustainable Tourism": "https://www.frontiersin.org/journals/sustainable-tourism/rss",
    "Frontiers in Synaptic Neuroscience": "https://www.frontiersin.org/journals/synaptic-neuroscience/rss",
    "Frontiers in Synthetic Biology": "https://www.frontiersin.org/journals/synthetic-biology/rss",
    "Frontiers in Systems Biology": "https://www.frontiersin.org/journals/systems-biology/rss",
    "Frontiers in Systems Neuroscience": "https://www.frontiersin.org/journals/systems-neuroscience/rss",
    "Frontiers in the Internet of Things": "https://www.frontiersin.org/journals/the-internet-of-things/rss",
    "Frontiers in Thermal Engineering": "https://www.frontiersin.org/journals/thermal-engineering/rss",
    "Frontiers in Toxicology": "https://www.frontiersin.org/journals/toxicology/rss",
    "Transplant International": "https://www.frontiersin.org/journals/transplant-international/rss",
    "Frontiers in Transplantation": "https://www.frontiersin.org/journals/transplantation/rss",
    "Frontiers in Tropical Diseases": "https://www.frontiersin.org/journals/tropical-diseases/rss",
    "Frontiers in Tuberculosis": "https://www.frontiersin.org/journals/tuberculosis/rss",
    "Frontiers in Urology": "https://www.frontiersin.org/journals/urology/rss",
    "Frontiers in Veterinary Science": "https://www.frontiersin.org/journals/veterinary-science/rss",
    "Frontiers in Virology": "https://www.frontiersin.org/journals/virology/rss",
    "Frontiers in Virtual Reality": "https://www.frontiersin.org/journals/virtual-reality/rss",
    "Frontiers in Water": "https://www.frontiersin.org/journals/water/rss",
    "Frontiers for Young Minds": "https://www.frontiersin.org/journals/frontiers-for-young-minds/rss",
}
