RSS_FEEDS: dict[str, str] = {
    "PLOS Biology": "https://journals.plos.org/plosbiology/feed/atom",
    "PLOS Climate": "https://journals.plos.org/climate/feed/atom",
    "PLOS Complex Systems": "https://journals.plos.org/complexsystems/feed/atom",
    "PLOS Computational Biology": "https://journals.plos.org/ploscompbiol/feed/atom",
    "PLOS Digital Health": "https://journals.plos.org/digitalhealth/feed/atom",
    "PLOS Genetics": "https://journals.plos.org/plosgenetics/feed/atom",
    "PLOS Global Public Health": "https://journals.plos.org/globalpublichealth/feed/atom",
    "PLOS Medicine": "https://journals.plos.org/plosmedicine/feed/atom",
    "PLOS Mental Health": "https://journals.plos.org/mentalhealth/feed/atom",
    "PLOS Neglected Tropical Diseases": "https://journals.plos.org/plosntds/feed/atom",
    "PLOS ONE": "https://journals.plos.org/plosone/feed/atom",
    "PLOS Pathogens": "https://journals.plos.org/plospathogens/feed/atom",
    "PLOS Sustainability and Transformation": "https://journals.plos.org/sustainabilitytransformation/feed/atom",
    "PLOS Water": "https://journals.plos.org/water/feed/atom",
}
